# Site settings
title: AOSN読書会
#email: webmaster@tasktoys.com
description: "AOSN読書会は、IT分野の技術書をオンラインで輪読する読書会です。"
copyright: "2014-2017 Alice on Sunday Nights Workshop"
baseurl: ""
url: "http://aosn.ws"
#twitter_username: jekyllrb
github_username:  aosn

# Build settings
markdown: kramdown
permalink: pretty

# Plugins
gems:
  - jemoji

emoji:
  src: "/assets/images"
